/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type CoreDashboardTransformer from '#transport/core/transformers/dashboard_transformer'
import type FileFileFolderTransformer from '#transport/file/transformers/file_folder_transformer'
import type FileFileTransformer from '#transport/file/transformers/file_transformer'
import type IdentityPermissionTransformer from '#transport/identity/transformers/permission_transformer'
import type IdentityRoleTransformer from '#transport/identity/transformers/role_transformer'
import type IdentityUserTransformer from '#transport/identity/transformers/user_transformer'
import type LogLogEntryTransformer from '#transport/log/transformers/log_entry_transformer'
import type InertiaMiddleware from '#transport/core/middleware/inertia_middleware'

export namespace Data {
  export namespace Core {
    export type Dashboard = InferData<CoreDashboardTransformer>
    export namespace Dashboard {
      export type Variants = InferVariants<CoreDashboardTransformer>
    }
  }
  export namespace File {
    export type FileFolder = InferData<FileFileFolderTransformer>
    export namespace FileFolder {
      export type Variants = InferVariants<FileFileFolderTransformer>
    }
    export type File = InferData<FileFileTransformer>
    export namespace File {
      export type Variants = InferVariants<FileFileTransformer>
    }
  }
  export namespace Identity {
    export type Permission = InferData<IdentityPermissionTransformer>
    export namespace Permission {
      export type Variants = InferVariants<IdentityPermissionTransformer>
    }
    export type Role = InferData<IdentityRoleTransformer>
    export namespace Role {
      export type Variants = InferVariants<IdentityRoleTransformer>
    }
    export type User = InferData<IdentityUserTransformer>
    export namespace User {
      export type Variants = InferVariants<IdentityUserTransformer>
    }
  }
  export namespace Log {
    export type LogEntry = InferData<LogLogEntryTransformer>
    export namespace LogEntry {
      export type Variants = InferVariants<LogLogEntryTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
