/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    front: {
      Account: () => import('#controllers/account/front/account_controller'),
      EmailChange: () => import('#controllers/account/front/email_change_controller'),
    },
  },
  auth: {
    cms: {
      Users: () => import('#controllers/auth/cms/users_controller'),
      UsersCreate: () => import('#controllers/auth/cms/users_create_controller'),
      UsersShow: () => import('#controllers/auth/cms/users_show_controller'),
      UsersUpdate: () => import('#controllers/auth/cms/users_update_controller'),
    },
    front: {
      AcceptInvitation: () => import('#controllers/auth/front/accept_invitation_controller'),
      EmailVerification: () => import('#controllers/auth/front/email_verification_controller'),
      ForgotPassword: () => import('#controllers/auth/front/forgot_password_controller'),
      Register: () => import('#controllers/auth/front/register_controller'),
      ResetPassword: () => import('#controllers/auth/front/reset_password_controller'),
      Session: () => import('#controllers/auth/front/session_controller'),
      Social: () => import('#controllers/auth/front/social_controller'),
    },
  },
  core: {
    cms: {
      Dashboard: () => import('#controllers/core/cms/dashboard_controller'),
    },
  },
  file: {
    api: {
      File: () => import('#controllers/file/api/file_controller'),
    },
    cms: {
      FileFolders: () => import('#controllers/file/cms/file_folders_controller'),
      Files: () => import('#controllers/file/cms/files_controller'),
    },
  },
  page: {
    api: {
      BuilderOperations: () => import('#controllers/page/api/builder_operations_controller'),
    },
    cms: {
      PageRevisions: () => import('#controllers/page/cms/page_revisions_controller'),
      PageTranslations: () => import('#controllers/page/cms/page_translations_controller'),
      Pages: () => import('#controllers/page/cms/pages_controller'),
      PagesCreate: () => import('#controllers/page/cms/pages_create_controller'),
      PagesPreview: () => import('#controllers/page/cms/pages_preview_controller'),
      PagesShow: () => import('#controllers/page/cms/pages_show_controller'),
      PagesUpdate: () => import('#controllers/page/cms/pages_update_controller'),
    },
    front: {
      Contact: () => import('#controllers/page/front/contact_controller'),
      Page: () => import('#controllers/page/front/page_controller'),
    },
  },
  preferences: {
    api: {
      Theme: () => import('#controllers/preferences/api/theme_controller'),
    },
    front: {
      Preferences: () => import('#controllers/preferences/front/preferences_controller'),
    },
  },
  profile: {
    front: {
      Profile: () => import('#controllers/profile/front/profile_controller'),
    },
  },
  template: {
    cms: {
      Templates: () => import('#controllers/template/cms/templates_controller'),
    },
  },
}
