/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type DashboardTransformer from '#transformers/dashboard_transformer'
import type FileFolderTransformer from '#transformers/file_folder_transformer'
import type FileTransformer from '#transformers/file_transformer'
import type LogEntryTransformer from '#transformers/log_entry_transformer'
import type PermissionTransformer from '#transformers/permission_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Dashboard = InferData<DashboardTransformer>
  export namespace Dashboard {
    export type Variants = InferVariants<DashboardTransformer>
  }
  export type FileFolder = InferData<FileFolderTransformer>
  export namespace FileFolder {
    export type Variants = InferVariants<FileFolderTransformer>
  }
  export type File = InferData<FileTransformer>
  export namespace File {
    export type Variants = InferVariants<FileTransformer>
  }
  export type LogEntry = InferData<LogEntryTransformer>
  export namespace LogEntry {
    export type Variants = InferVariants<LogEntryTransformer>
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
