/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type FileFolderTransformer from '#transformers/file_folder_transformer'
import type FileTransformer from '#transformers/file_transformer'
import type PageRevisionTransformer from '#transformers/page_revision_transformer'
import type PageTransformer from '#transformers/page_transformer'
import type PageTranslationTransformer from '#transformers/page_translation_transformer'
import type PermissionTransformer from '#transformers/permission_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type TemplateTransformer from '#transformers/template_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type FileFolder = InferData<FileFolderTransformer>
  export namespace FileFolder {
    export type Variants = InferVariants<FileFolderTransformer>
  }
  export type File = InferData<FileTransformer>
  export namespace File {
    export type Variants = InferVariants<FileTransformer>
  }
  export type PageRevision = InferData<PageRevisionTransformer>
  export namespace PageRevision {
    export type Variants = InferVariants<PageRevisionTransformer>
  }
  export type Page = InferData<PageTransformer>
  export namespace Page {
    export type Variants = InferVariants<PageTransformer>
  }
  export type PageTranslation = InferData<PageTranslationTransformer>
  export namespace PageTranslation {
    export type Variants = InferVariants<PageTranslationTransformer>
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type Template = InferData<TemplateTransformer>
  export namespace Template {
    export type Variants = InferVariants<TemplateTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
