/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'drive.fs.serve': {
    methods: ["GET","HEAD"],
    pattern: '/uploads/*',
    tokens: [{"old":"/uploads/*","type":0,"val":"uploads","end":""},{"old":"/uploads/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['drive.fs.serve']['types'],
  },
  'admin.file.files.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/files',
    tokens: [{"old":"/admin/files","type":0,"val":"admin","end":""},{"old":"/admin/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['admin.file.files.render']['types'],
  },
  'admin.file.files.upload': {
    methods: ["POST"],
    pattern: '/admin/files/upload',
    tokens: [{"old":"/admin/files/upload","type":0,"val":"admin","end":""},{"old":"/admin/files/upload","type":0,"val":"files","end":""},{"old":"/admin/files/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['admin.file.files.upload']['types'],
  },
  'admin.file.files.move': {
    methods: ["POST"],
    pattern: '/admin/files/:id/move',
    tokens: [{"old":"/admin/files/:id/move","type":0,"val":"admin","end":""},{"old":"/admin/files/:id/move","type":0,"val":"files","end":""},{"old":"/admin/files/:id/move","type":1,"val":"id","end":""},{"old":"/admin/files/:id/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['admin.file.files.move']['types'],
  },
  'admin.file.files.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/files/:id',
    tokens: [{"old":"/admin/files/:id","type":0,"val":"admin","end":""},{"old":"/admin/files/:id","type":0,"val":"files","end":""},{"old":"/admin/files/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.file.files.destroy']['types'],
  },
  'admin.file.files.upsert_alt': {
    methods: ["POST"],
    pattern: '/admin/files/:id/alts',
    tokens: [{"old":"/admin/files/:id/alts","type":0,"val":"admin","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"files","end":""},{"old":"/admin/files/:id/alts","type":1,"val":"id","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"alts","end":""}],
    types: placeholder as Registry['admin.file.files.upsert_alt']['types'],
  },
  'admin.file.files.delete_alt': {
    methods: ["DELETE"],
    pattern: '/admin/files/:id/alts',
    tokens: [{"old":"/admin/files/:id/alts","type":0,"val":"admin","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"files","end":""},{"old":"/admin/files/:id/alts","type":1,"val":"id","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"alts","end":""}],
    types: placeholder as Registry['admin.file.files.delete_alt']['types'],
  },
  'admin.file.file_folders.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/files/folders',
    tokens: [{"old":"/admin/files/folders","type":0,"val":"admin","end":""},{"old":"/admin/files/folders","type":0,"val":"files","end":""},{"old":"/admin/files/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.file.file_folders.render']['types'],
  },
  'admin.file.file_folders.execute': {
    methods: ["POST"],
    pattern: '/admin/files/folders',
    tokens: [{"old":"/admin/files/folders","type":0,"val":"admin","end":""},{"old":"/admin/files/folders","type":0,"val":"files","end":""},{"old":"/admin/files/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.file.file_folders.execute']['types'],
  },
  'admin.file.file_folders.update': {
    methods: ["PUT"],
    pattern: '/admin/files/folders/:id',
    tokens: [{"old":"/admin/files/folders/:id","type":0,"val":"admin","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"files","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"folders","end":""},{"old":"/admin/files/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.file.file_folders.update']['types'],
  },
  'admin.file.file_folders.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/files/folders/:id',
    tokens: [{"old":"/admin/files/folders/:id","type":0,"val":"admin","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"files","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"folders","end":""},{"old":"/admin/files/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.file.file_folders.destroy']['types'],
  },
  'admin.identity.users.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.identity.users.render']['types'],
  },
  'admin.identity.users_create.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/create',
    tokens: [{"old":"/admin/users/create","type":0,"val":"admin","end":""},{"old":"/admin/users/create","type":0,"val":"users","end":""},{"old":"/admin/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.identity.users_create.render']['types'],
  },
  'admin.identity.users_create.execute': {
    methods: ["POST"],
    pattern: '/admin/users/create',
    tokens: [{"old":"/admin/users/create","type":0,"val":"admin","end":""},{"old":"/admin/users/create","type":0,"val":"users","end":""},{"old":"/admin/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.identity.users_create.execute']['types'],
  },
  'admin.identity.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.identity.users.destroy']['types'],
  },
  'admin.identity.users_show.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.identity.users_show.render']['types'],
  },
  'admin.identity.users_update.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id/edit',
    tokens: [{"old":"/admin/users/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"users","end":""},{"old":"/admin/users/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.identity.users_update.render']['types'],
  },
  'admin.identity.users_update.execute': {
    methods: ["POST"],
    pattern: '/admin/users/:id/edit',
    tokens: [{"old":"/admin/users/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"users","end":""},{"old":"/admin/users/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.identity.users_update.execute']['types'],
  },
  'admin.identity.roles.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.identity.roles.render']['types'],
  },
  'admin.identity.roles_create.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/create',
    tokens: [{"old":"/admin/roles/create","type":0,"val":"admin","end":""},{"old":"/admin/roles/create","type":0,"val":"roles","end":""},{"old":"/admin/roles/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.identity.roles_create.render']['types'],
  },
  'admin.identity.roles_create.execute': {
    methods: ["POST"],
    pattern: '/admin/roles/create',
    tokens: [{"old":"/admin/roles/create","type":0,"val":"admin","end":""},{"old":"/admin/roles/create","type":0,"val":"roles","end":""},{"old":"/admin/roles/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.identity.roles_create.execute']['types'],
  },
  'admin.identity.roles.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.identity.roles.destroy']['types'],
  },
  'admin.identity.roles_show.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.identity.roles_show.render']['types'],
  },
  'admin.identity.roles_update.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id/edit',
    tokens: [{"old":"/admin/roles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.identity.roles_update.render']['types'],
  },
  'admin.identity.roles_update.execute': {
    methods: ["POST"],
    pattern: '/admin/roles/:id/edit',
    tokens: [{"old":"/admin/roles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.identity.roles_update.execute']['types'],
  },
  'admin.identity.permissions.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions',
    tokens: [{"old":"/admin/permissions","type":0,"val":"admin","end":""},{"old":"/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['admin.identity.permissions.render']['types'],
  },
  'admin.identity.permissions_create.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions/create',
    tokens: [{"old":"/admin/permissions/create","type":0,"val":"admin","end":""},{"old":"/admin/permissions/create","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.identity.permissions_create.render']['types'],
  },
  'admin.identity.permissions_create.execute': {
    methods: ["POST"],
    pattern: '/admin/permissions/create',
    tokens: [{"old":"/admin/permissions/create","type":0,"val":"admin","end":""},{"old":"/admin/permissions/create","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.identity.permissions_create.execute']['types'],
  },
  'admin.identity.permissions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/permissions/:id',
    tokens: [{"old":"/admin/permissions/:id","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.identity.permissions.destroy']['types'],
  },
  'admin.identity.permissions_update.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions/:id/edit',
    tokens: [{"old":"/admin/permissions/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.identity.permissions_update.render']['types'],
  },
  'admin.identity.permissions_update.execute': {
    methods: ["POST"],
    pattern: '/admin/permissions/:id/edit',
    tokens: [{"old":"/admin/permissions/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.identity.permissions_update.execute']['types'],
  },
  'admin.log.logs.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/logs',
    tokens: [{"old":"/admin/logs","type":0,"val":"admin","end":""},{"old":"/admin/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['admin.log.logs.render']['types'],
  },
  'admin.core.dashboard.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['admin.core.dashboard.render']['types'],
  },
  'admin.core.maintenance.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/maintenance',
    tokens: [{"old":"/admin/settings/maintenance","type":0,"val":"admin","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"settings","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['admin.core.maintenance.render']['types'],
  },
  'admin.core.maintenance.update': {
    methods: ["POST"],
    pattern: '/admin/settings/maintenance',
    tokens: [{"old":"/admin/settings/maintenance","type":0,"val":"admin","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"settings","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['admin.core.maintenance.update']['types'],
  },
  'admin.core.maintenance.toggle': {
    methods: ["POST"],
    pattern: '/admin/settings/maintenance/toggle',
    tokens: [{"old":"/admin/settings/maintenance/toggle","type":0,"val":"admin","end":""},{"old":"/admin/settings/maintenance/toggle","type":0,"val":"settings","end":""},{"old":"/admin/settings/maintenance/toggle","type":0,"val":"maintenance","end":""},{"old":"/admin/settings/maintenance/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['admin.core.maintenance.toggle']['types'],
  },
  'core.sitemap.show': {
    methods: ["GET","HEAD"],
    pattern: '/sitemap.xml',
    tokens: [{"old":"/sitemap.xml","type":0,"val":"sitemap.xml","end":""}],
    types: placeholder as Registry['core.sitemap.show']['types'],
  },
  'core.robots.show': {
    methods: ["GET","HEAD"],
    pattern: '/robots.txt',
    tokens: [{"old":"/robots.txt","type":0,"val":"robots.txt","end":""}],
    types: placeholder as Registry['core.robots.show']['types'],
  },
  'core.docs.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/docs',
    tokens: [{"old":"/api/docs","type":0,"val":"api","end":""},{"old":"/api/docs","type":0,"val":"docs","end":""}],
    types: placeholder as Registry['core.docs.show']['types'],
  },
  'account.profile.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/profile',
    tokens: [{"old":"/settings/profile","type":0,"val":"settings","end":""},{"old":"/settings/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['account.profile.render']['types'],
  },
  'account.profile.execute': {
    methods: ["POST"],
    pattern: '/settings/profile',
    tokens: [{"old":"/settings/profile","type":0,"val":"settings","end":""},{"old":"/settings/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['account.profile.execute']['types'],
  },
  'account.account.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['account.account.render']['types'],
  },
  'account.account.execute': {
    methods: ["POST"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['account.account.execute']['types'],
  },
  'account.account.destroy': {
    methods: ["DELETE"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['account.account.destroy']['types'],
  },
  'account.email_change.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/account/email_change/:token',
    tokens: [{"old":"/settings/account/email_change/:token","type":0,"val":"settings","end":""},{"old":"/settings/account/email_change/:token","type":0,"val":"account","end":""},{"old":"/settings/account/email_change/:token","type":0,"val":"email_change","end":""},{"old":"/settings/account/email_change/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['account.email_change.render']['types'],
  },
  'account.email_change.execute': {
    methods: ["POST"],
    pattern: '/settings/account/email_change',
    tokens: [{"old":"/settings/account/email_change","type":0,"val":"settings","end":""},{"old":"/settings/account/email_change","type":0,"val":"account","end":""},{"old":"/settings/account/email_change","type":0,"val":"email_change","end":""}],
    types: placeholder as Registry['account.email_change.execute']['types'],
  },
  'account.preferences.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/preferences',
    tokens: [{"old":"/settings/preferences","type":0,"val":"settings","end":""},{"old":"/settings/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['account.preferences.render']['types'],
  },
  'account.preferences.execute': {
    methods: ["POST"],
    pattern: '/settings/preferences',
    tokens: [{"old":"/settings/preferences","type":0,"val":"settings","end":""},{"old":"/settings/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['account.preferences.execute']['types'],
  },
  'account.index': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['account.index']['types'],
  },
  'api.v1.account.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/profile',
    tokens: [{"old":"/api/v1/profile","type":0,"val":"api","end":""},{"old":"/api/v1/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['api.v1.account.profile.show']['types'],
  },
  'api.v1.account.profile.update': {
    methods: ["PUT"],
    pattern: '/api/v1/profile',
    tokens: [{"old":"/api/v1/profile","type":0,"val":"api","end":""},{"old":"/api/v1/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['api.v1.account.profile.update']['types'],
  },
  'api.v1.account.account.update': {
    methods: ["PUT"],
    pattern: '/api/v1/account',
    tokens: [{"old":"/api/v1/account","type":0,"val":"api","end":""},{"old":"/api/v1/account","type":0,"val":"v1","end":""},{"old":"/api/v1/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['api.v1.account.account.update']['types'],
  },
  'api.v1.account.account.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/account',
    tokens: [{"old":"/api/v1/account","type":0,"val":"api","end":""},{"old":"/api/v1/account","type":0,"val":"v1","end":""},{"old":"/api/v1/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['api.v1.account.account.destroy']['types'],
  },
  'api.v1.admin.account.preferences.execute': {
    methods: ["POST"],
    pattern: '/api/v1/admin/preferences/theme',
    tokens: [{"old":"/api/v1/admin/preferences/theme","type":0,"val":"api","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"preferences","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"theme","end":""}],
    types: placeholder as Registry['api.v1.admin.account.preferences.execute']['types'],
  },
  'auth.session.render': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.session.render']['types'],
  },
  'auth.session.execute': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.session.execute']['types'],
  },
  'auth.two_factor.render': {
    methods: ["GET","HEAD"],
    pattern: '/two-factor',
    tokens: [{"old":"/two-factor","type":0,"val":"two-factor","end":""}],
    types: placeholder as Registry['auth.two_factor.render']['types'],
  },
  'auth.two_factor.verify': {
    methods: ["POST"],
    pattern: '/two-factor',
    tokens: [{"old":"/two-factor","type":0,"val":"two-factor","end":""}],
    types: placeholder as Registry['auth.two_factor.verify']['types'],
  },
  'auth.register.render': {
    methods: ["GET","HEAD"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register.render']['types'],
  },
  'auth.register.execute': {
    methods: ["POST"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register.execute']['types'],
  },
  'auth.forgot_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password.render']['types'],
  },
  'auth.forgot_password.execute': {
    methods: ["POST"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password.execute']['types'],
  },
  'auth.reset_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/reset-password/:token',
    tokens: [{"old":"/reset-password/:token","type":0,"val":"reset-password","end":""},{"old":"/reset-password/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['auth.reset_password.render']['types'],
  },
  'auth.reset_password.execute': {
    methods: ["POST"],
    pattern: '/reset-password',
    tokens: [{"old":"/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['auth.reset_password.execute']['types'],
  },
  'auth.accept_invitation.render': {
    methods: ["GET","HEAD"],
    pattern: '/accept-invitation/:token',
    tokens: [{"old":"/accept-invitation/:token","type":0,"val":"accept-invitation","end":""},{"old":"/accept-invitation/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['auth.accept_invitation.render']['types'],
  },
  'auth.accept_invitation.execute': {
    methods: ["POST"],
    pattern: '/accept-invitation',
    tokens: [{"old":"/accept-invitation","type":0,"val":"accept-invitation","end":""}],
    types: placeholder as Registry['auth.accept_invitation.execute']['types'],
  },
  'auth.session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.session.destroy']['types'],
  },
  'auth.email_verification.execute': {
    methods: ["GET","HEAD"],
    pattern: '/verify/:token',
    tokens: [{"old":"/verify/:token","type":0,"val":"verify","end":""},{"old":"/verify/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['auth.email_verification.execute']['types'],
  },
  'auth.social.render': {
    methods: ["GET","HEAD"],
    pattern: '/oauth/define-password',
    tokens: [{"old":"/oauth/define-password","type":0,"val":"oauth","end":""},{"old":"/oauth/define-password","type":0,"val":"define-password","end":""}],
    types: placeholder as Registry['auth.social.render']['types'],
  },
  'auth.social.execute': {
    methods: ["POST"],
    pattern: '/oauth/define-password',
    tokens: [{"old":"/oauth/define-password","type":0,"val":"oauth","end":""},{"old":"/oauth/define-password","type":0,"val":"define-password","end":""}],
    types: placeholder as Registry['auth.social.execute']['types'],
  },
  'auth.social.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/oauth/:provider',
    tokens: [{"old":"/oauth/:provider","type":0,"val":"oauth","end":""},{"old":"/oauth/:provider","type":1,"val":"provider","end":""}],
    types: placeholder as Registry['auth.social.redirect']['types'],
  },
  'auth.social.callback': {
    methods: ["GET","HEAD"],
    pattern: '/oauth/:provider/callback',
    tokens: [{"old":"/oauth/:provider/callback","type":0,"val":"oauth","end":""},{"old":"/oauth/:provider/callback","type":1,"val":"provider","end":""},{"old":"/oauth/:provider/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['auth.social.callback']['types'],
  },
  'auth.social.unlink': {
    methods: ["POST"],
    pattern: '/oauth/:provider/unlink',
    tokens: [{"old":"/oauth/:provider/unlink","type":0,"val":"oauth","end":""},{"old":"/oauth/:provider/unlink","type":1,"val":"provider","end":""},{"old":"/oauth/:provider/unlink","type":0,"val":"unlink","end":""}],
    types: placeholder as Registry['auth.social.unlink']['types'],
  },
  'api.v1.auth.login.execute': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['api.v1.auth.login.execute']['types'],
  },
  'api.v1.auth.register.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/register',
    tokens: [{"old":"/api/v1/auth/register","type":0,"val":"api","end":""},{"old":"/api/v1/auth/register","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/register","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['api.v1.auth.register.store']['types'],
  },
  'api.v1.auth.forgot_password.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/forgot-password',
    tokens: [{"old":"/api/v1/auth/forgot-password","type":0,"val":"api","end":""},{"old":"/api/v1/auth/forgot-password","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/forgot-password","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['api.v1.auth.forgot_password.store']['types'],
  },
  'api.v1.auth.reset_password.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/reset-password',
    tokens: [{"old":"/api/v1/auth/reset-password","type":0,"val":"api","end":""},{"old":"/api/v1/auth/reset-password","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/reset-password","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['api.v1.auth.reset_password.store']['types'],
  },
  'api.v1.auth.email_verification.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/verify-email/:token',
    tokens: [{"old":"/api/v1/auth/verify-email/:token","type":0,"val":"api","end":""},{"old":"/api/v1/auth/verify-email/:token","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/verify-email/:token","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/verify-email/:token","type":0,"val":"verify-email","end":""},{"old":"/api/v1/auth/verify-email/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['api.v1.auth.email_verification.store']['types'],
  },
  'api.v1.auth.accept_invitation.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/accept-invitation',
    tokens: [{"old":"/api/v1/auth/accept-invitation","type":0,"val":"api","end":""},{"old":"/api/v1/auth/accept-invitation","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/accept-invitation","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/accept-invitation","type":0,"val":"accept-invitation","end":""}],
    types: placeholder as Registry['api.v1.auth.accept_invitation.store']['types'],
  },
  'api.v1.auth.logout.destroy': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['api.v1.auth.logout.destroy']['types'],
  },
  'api.v1.auth.me.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/me',
    tokens: [{"old":"/api/v1/auth/me","type":0,"val":"api","end":""},{"old":"/api/v1/auth/me","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/me","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['api.v1.auth.me.show']['types'],
  },
  'api.v1.admin.file.files.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/files',
    tokens: [{"old":"/api/v1/admin/files","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.index']['types'],
  },
  'api.v1.admin.file.files.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/files',
    tokens: [{"old":"/api/v1/admin/files","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.store']['types'],
  },
  'api.v1.admin.file.files.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/files/:id',
    tokens: [{"old":"/api/v1/admin/files/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.show']['types'],
  },
  'api.v1.admin.file.files.move': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/files/:id/move',
    tokens: [{"old":"/api/v1/admin/files/:id/move","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id/move","type":1,"val":"id","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.move']['types'],
  },
  'api.v1.admin.file.files.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/files/:id',
    tokens: [{"old":"/api/v1/admin/files/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.destroy']['types'],
  },
  'api.v1.admin.file.files.upsert_alt': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/files/:id/alt',
    tokens: [{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id/alt","type":1,"val":"id","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"alt","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.upsert_alt']['types'],
  },
  'api.v1.admin.file.files.delete_alt': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/files/:id/alt',
    tokens: [{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id/alt","type":1,"val":"id","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"alt","end":""}],
    types: placeholder as Registry['api.v1.admin.file.files.delete_alt']['types'],
  },
  'api.v1.admin.file.folders.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/folders',
    tokens: [{"old":"/api/v1/admin/folders","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['api.v1.admin.file.folders.index']['types'],
  },
  'api.v1.admin.file.folders.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/folders',
    tokens: [{"old":"/api/v1/admin/folders","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['api.v1.admin.file.folders.store']['types'],
  },
  'api.v1.admin.file.folders.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/folders/:id',
    tokens: [{"old":"/api/v1/admin/folders/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.file.folders.show']['types'],
  },
  'api.v1.admin.file.folders.children': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/folders/:id/children',
    tokens: [{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id/children","type":1,"val":"id","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"children","end":""}],
    types: placeholder as Registry['api.v1.admin.file.folders.children']['types'],
  },
  'api.v1.admin.file.folders.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/folders/:id',
    tokens: [{"old":"/api/v1/admin/folders/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.file.folders.update']['types'],
  },
  'api.v1.admin.file.folders.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/folders/:id',
    tokens: [{"old":"/api/v1/admin/folders/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.file.folders.destroy']['types'],
  },
  'api.v1.admin.identity.users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.users.index']['types'],
  },
  'api.v1.admin.identity.users.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.users.store']['types'],
  },
  'api.v1.admin.identity.users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.users.show']['types'],
  },
  'api.v1.admin.identity.users.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.users.update']['types'],
  },
  'api.v1.admin.identity.users.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.users.destroy']['types'],
  },
  'api.v1.admin.identity.roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/roles',
    tokens: [{"old":"/api/v1/admin/roles","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.roles.index']['types'],
  },
  'api.v1.admin.identity.roles.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/roles',
    tokens: [{"old":"/api/v1/admin/roles","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.roles.store']['types'],
  },
  'api.v1.admin.identity.roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.roles.show']['types'],
  },
  'api.v1.admin.identity.roles.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.roles.update']['types'],
  },
  'api.v1.admin.identity.roles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.roles.destroy']['types'],
  },
  'api.v1.admin.identity.permissions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/permissions',
    tokens: [{"old":"/api/v1/admin/permissions","type":0,"val":"api","end":""},{"old":"/api/v1/admin/permissions","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/permissions","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['api.v1.admin.identity.permissions.index']['types'],
  },
  'api.v1.admin.log.logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/logs',
    tokens: [{"old":"/api/v1/admin/logs","type":0,"val":"api","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['api.v1.admin.log.logs.index']['types'],
  },
  'api.v1.admin.core.dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/dashboard',
    tokens: [{"old":"/api/v1/admin/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/admin/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['api.v1.admin.core.dashboard.index']['types'],
  },
  'api.v1.admin.core.maintenance.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/maintenance',
    tokens: [{"old":"/api/v1/admin/maintenance","type":0,"val":"api","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['api.v1.admin.core.maintenance.index']['types'],
  },
  'api.v1.admin.core.maintenance.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/maintenance',
    tokens: [{"old":"/api/v1/admin/maintenance","type":0,"val":"api","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['api.v1.admin.core.maintenance.update']['types'],
  },
  'api.v1.admin.core.maintenance.toggle': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/maintenance/toggle',
    tokens: [{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"api","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"maintenance","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['api.v1.admin.core.maintenance.toggle']['types'],
  },
  'core.openapi.spec': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/openapi.json',
    tokens: [{"old":"/api/v1/openapi.json","type":0,"val":"api","end":""},{"old":"/api/v1/openapi.json","type":0,"val":"v1","end":""},{"old":"/api/v1/openapi.json","type":0,"val":"openapi.json","end":""}],
    types: placeholder as Registry['core.openapi.spec']['types'],
  },
  'health.liveness': {
    methods: ["GET","HEAD"],
    pattern: '/health',
    tokens: [{"old":"/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['health.liveness']['types'],
  },
  'health.readiness': {
    methods: ["GET","HEAD"],
    pattern: '/health/ready',
    tokens: [{"old":"/health/ready","type":0,"val":"health","end":""},{"old":"/health/ready","type":0,"val":"ready","end":""}],
    types: placeholder as Registry['health.readiness']['types'],
  },
  'core.home.render': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['core.home.render']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
