/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'drive.fs.serve': {
    methods: ["GET","HEAD"],
    pattern: '/uploads/*',
    tokens: [{"old":"/uploads/*","type":0,"val":"uploads","end":""},{"old":"/uploads/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['drive.fs.serve']['types'],
  },
  'health.liveness': {
    methods: ["GET","HEAD"],
    pattern: '/health',
    tokens: [{"old":"/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['health.liveness']['types'],
  },
  'health.readiness': {
    methods: ["GET","HEAD"],
    pattern: '/health/ready',
    tokens: [{"old":"/health/ready","type":0,"val":"health","end":""},{"old":"/health/ready","type":0,"val":"ready","end":""}],
    types: placeholder as Registry['health.readiness']['types'],
  },
  'sitemap.show': {
    methods: ["GET","HEAD"],
    pattern: '/sitemap.xml',
    tokens: [{"old":"/sitemap.xml","type":0,"val":"sitemap.xml","end":""}],
    types: placeholder as Registry['sitemap.show']['types'],
  },
  'robots.show': {
    methods: ["GET","HEAD"],
    pattern: '/robots.txt',
    tokens: [{"old":"/robots.txt","type":0,"val":"robots.txt","end":""}],
    types: placeholder as Registry['robots.show']['types'],
  },
  'front.home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['front.home']['types'],
  },
  'front.services': {
    methods: ["GET","HEAD"],
    pattern: '/services',
    tokens: [{"old":"/services","type":0,"val":"services","end":""}],
    types: placeholder as Registry['front.services']['types'],
  },
  'front.projects': {
    methods: ["GET","HEAD"],
    pattern: '/projets',
    tokens: [{"old":"/projets","type":0,"val":"projets","end":""}],
    types: placeholder as Registry['front.projects']['types'],
  },
  'front.projects.show': {
    methods: ["GET","HEAD"],
    pattern: '/projets/:slug',
    tokens: [{"old":"/projets/:slug","type":0,"val":"projets","end":""},{"old":"/projets/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['front.projects.show']['types'],
  },
  'auth.session.render': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.session.render']['types'],
  },
  'auth.session.execute': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.session.execute']['types'],
  },
  'auth.register.render': {
    methods: ["GET","HEAD"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register.render']['types'],
  },
  'auth.register.execute': {
    methods: ["POST"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register.execute']['types'],
  },
  'auth.forgot_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password.render']['types'],
  },
  'auth.forgot_password.execute': {
    methods: ["POST"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password.execute']['types'],
  },
  'auth.reset_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/reset-password/:token',
    tokens: [{"old":"/reset-password/:token","type":0,"val":"reset-password","end":""},{"old":"/reset-password/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['auth.reset_password.render']['types'],
  },
  'auth.reset_password.execute': {
    methods: ["POST"],
    pattern: '/reset-password',
    tokens: [{"old":"/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['auth.reset_password.execute']['types'],
  },
  'auth.accept_invitation.render': {
    methods: ["GET","HEAD"],
    pattern: '/accept-invitation/:token',
    tokens: [{"old":"/accept-invitation/:token","type":0,"val":"accept-invitation","end":""},{"old":"/accept-invitation/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['auth.accept_invitation.render']['types'],
  },
  'auth.accept_invitation.execute': {
    methods: ["POST"],
    pattern: '/accept-invitation',
    tokens: [{"old":"/accept-invitation","type":0,"val":"accept-invitation","end":""}],
    types: placeholder as Registry['auth.accept_invitation.execute']['types'],
  },
  'auth.session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.session.destroy']['types'],
  },
  'auth.email_verification.execute': {
    methods: ["GET","HEAD"],
    pattern: '/verify/:token',
    tokens: [{"old":"/verify/:token","type":0,"val":"verify","end":""},{"old":"/verify/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['auth.email_verification.execute']['types'],
  },
  'auth.social.render': {
    methods: ["GET","HEAD"],
    pattern: '/oauth/define-password',
    tokens: [{"old":"/oauth/define-password","type":0,"val":"oauth","end":""},{"old":"/oauth/define-password","type":0,"val":"define-password","end":""}],
    types: placeholder as Registry['auth.social.render']['types'],
  },
  'auth.social.execute': {
    methods: ["POST"],
    pattern: '/oauth/define-password',
    tokens: [{"old":"/oauth/define-password","type":0,"val":"oauth","end":""},{"old":"/oauth/define-password","type":0,"val":"define-password","end":""}],
    types: placeholder as Registry['auth.social.execute']['types'],
  },
  'auth.social.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/oauth/:provider',
    tokens: [{"old":"/oauth/:provider","type":0,"val":"oauth","end":""},{"old":"/oauth/:provider","type":1,"val":"provider","end":""}],
    types: placeholder as Registry['auth.social.redirect']['types'],
  },
  'auth.social.callback': {
    methods: ["GET","HEAD"],
    pattern: '/oauth/:provider/callback',
    tokens: [{"old":"/oauth/:provider/callback","type":0,"val":"oauth","end":""},{"old":"/oauth/:provider/callback","type":1,"val":"provider","end":""},{"old":"/oauth/:provider/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['auth.social.callback']['types'],
  },
  'auth.social.unlink': {
    methods: ["POST"],
    pattern: '/oauth/:provider/unlink',
    tokens: [{"old":"/oauth/:provider/unlink","type":0,"val":"oauth","end":""},{"old":"/oauth/:provider/unlink","type":1,"val":"provider","end":""},{"old":"/oauth/:provider/unlink","type":0,"val":"unlink","end":""}],
    types: placeholder as Registry['auth.social.unlink']['types'],
  },
  'settings.profile.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/profile',
    tokens: [{"old":"/settings/profile","type":0,"val":"settings","end":""},{"old":"/settings/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['settings.profile.render']['types'],
  },
  'settings.profile.execute': {
    methods: ["POST"],
    pattern: '/settings/profile',
    tokens: [{"old":"/settings/profile","type":0,"val":"settings","end":""},{"old":"/settings/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['settings.profile.execute']['types'],
  },
  'settings.account.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['settings.account.render']['types'],
  },
  'settings.account.execute': {
    methods: ["POST"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['settings.account.execute']['types'],
  },
  'settings.account.destroy': {
    methods: ["DELETE"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['settings.account.destroy']['types'],
  },
  'settings.email_change.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/account/email_change/:token',
    tokens: [{"old":"/settings/account/email_change/:token","type":0,"val":"settings","end":""},{"old":"/settings/account/email_change/:token","type":0,"val":"account","end":""},{"old":"/settings/account/email_change/:token","type":0,"val":"email_change","end":""},{"old":"/settings/account/email_change/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['settings.email_change.render']['types'],
  },
  'settings.email_change.execute': {
    methods: ["POST"],
    pattern: '/settings/account/email_change',
    tokens: [{"old":"/settings/account/email_change","type":0,"val":"settings","end":""},{"old":"/settings/account/email_change","type":0,"val":"account","end":""},{"old":"/settings/account/email_change","type":0,"val":"email_change","end":""}],
    types: placeholder as Registry['settings.email_change.execute']['types'],
  },
  'settings.preferences.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/preferences',
    tokens: [{"old":"/settings/preferences","type":0,"val":"settings","end":""},{"old":"/settings/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['settings.preferences.render']['types'],
  },
  'settings.preferences.execute': {
    methods: ["POST"],
    pattern: '/settings/preferences',
    tokens: [{"old":"/settings/preferences","type":0,"val":"settings","end":""},{"old":"/settings/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['settings.preferences.execute']['types'],
  },
  'settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.index']['types'],
  },
  'admin.dashboard.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['admin.dashboard.render']['types'],
  },
  'admin.users.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.render']['types'],
  },
  'admin.users_create.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/create',
    tokens: [{"old":"/admin/users/create","type":0,"val":"admin","end":""},{"old":"/admin/users/create","type":0,"val":"users","end":""},{"old":"/admin/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.users_create.render']['types'],
  },
  'admin.users_create.execute': {
    methods: ["POST"],
    pattern: '/admin/users/create',
    tokens: [{"old":"/admin/users/create","type":0,"val":"admin","end":""},{"old":"/admin/users/create","type":0,"val":"users","end":""},{"old":"/admin/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.users_create.execute']['types'],
  },
  'admin.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.destroy']['types'],
  },
  'admin.users_show.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users_show.render']['types'],
  },
  'admin.users_update.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id/edit',
    tokens: [{"old":"/admin/users/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"users","end":""},{"old":"/admin/users/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.users_update.render']['types'],
  },
  'admin.users_update.execute': {
    methods: ["POST"],
    pattern: '/admin/users/:id/edit',
    tokens: [{"old":"/admin/users/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"users","end":""},{"old":"/admin/users/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.users_update.execute']['types'],
  },
  'admin.roles.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.roles.render']['types'],
  },
  'admin.roles_create.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/create',
    tokens: [{"old":"/admin/roles/create","type":0,"val":"admin","end":""},{"old":"/admin/roles/create","type":0,"val":"roles","end":""},{"old":"/admin/roles/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.roles_create.render']['types'],
  },
  'admin.roles_create.execute': {
    methods: ["POST"],
    pattern: '/admin/roles/create',
    tokens: [{"old":"/admin/roles/create","type":0,"val":"admin","end":""},{"old":"/admin/roles/create","type":0,"val":"roles","end":""},{"old":"/admin/roles/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.roles_create.execute']['types'],
  },
  'admin.roles.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.roles.destroy']['types'],
  },
  'admin.roles_show.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.roles_show.render']['types'],
  },
  'admin.roles_update.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id/edit',
    tokens: [{"old":"/admin/roles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.roles_update.render']['types'],
  },
  'admin.roles_update.execute': {
    methods: ["POST"],
    pattern: '/admin/roles/:id/edit',
    tokens: [{"old":"/admin/roles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.roles_update.execute']['types'],
  },
  'admin.permissions.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions',
    tokens: [{"old":"/admin/permissions","type":0,"val":"admin","end":""},{"old":"/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['admin.permissions.render']['types'],
  },
  'admin.permissions_create.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions/create',
    tokens: [{"old":"/admin/permissions/create","type":0,"val":"admin","end":""},{"old":"/admin/permissions/create","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.permissions_create.render']['types'],
  },
  'admin.permissions_create.execute': {
    methods: ["POST"],
    pattern: '/admin/permissions/create',
    tokens: [{"old":"/admin/permissions/create","type":0,"val":"admin","end":""},{"old":"/admin/permissions/create","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.permissions_create.execute']['types'],
  },
  'admin.permissions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/permissions/:id',
    tokens: [{"old":"/admin/permissions/:id","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.permissions.destroy']['types'],
  },
  'admin.permissions_update.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions/:id/edit',
    tokens: [{"old":"/admin/permissions/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.permissions_update.render']['types'],
  },
  'admin.permissions_update.execute': {
    methods: ["POST"],
    pattern: '/admin/permissions/:id/edit',
    tokens: [{"old":"/admin/permissions/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/permissions/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.permissions_update.execute']['types'],
  },
  'admin.files.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/files',
    tokens: [{"old":"/admin/files","type":0,"val":"admin","end":""},{"old":"/admin/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['admin.files.render']['types'],
  },
  'admin.files.upload': {
    methods: ["POST"],
    pattern: '/admin/files/upload',
    tokens: [{"old":"/admin/files/upload","type":0,"val":"admin","end":""},{"old":"/admin/files/upload","type":0,"val":"files","end":""},{"old":"/admin/files/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['admin.files.upload']['types'],
  },
  'admin.files.move': {
    methods: ["POST"],
    pattern: '/admin/files/:id/move',
    tokens: [{"old":"/admin/files/:id/move","type":0,"val":"admin","end":""},{"old":"/admin/files/:id/move","type":0,"val":"files","end":""},{"old":"/admin/files/:id/move","type":1,"val":"id","end":""},{"old":"/admin/files/:id/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['admin.files.move']['types'],
  },
  'admin.files.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/files/:id',
    tokens: [{"old":"/admin/files/:id","type":0,"val":"admin","end":""},{"old":"/admin/files/:id","type":0,"val":"files","end":""},{"old":"/admin/files/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.files.destroy']['types'],
  },
  'admin.files.upsert_alt': {
    methods: ["POST"],
    pattern: '/admin/files/:id/alts',
    tokens: [{"old":"/admin/files/:id/alts","type":0,"val":"admin","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"files","end":""},{"old":"/admin/files/:id/alts","type":1,"val":"id","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"alts","end":""}],
    types: placeholder as Registry['admin.files.upsert_alt']['types'],
  },
  'admin.files.delete_alt': {
    methods: ["DELETE"],
    pattern: '/admin/files/:id/alts',
    tokens: [{"old":"/admin/files/:id/alts","type":0,"val":"admin","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"files","end":""},{"old":"/admin/files/:id/alts","type":1,"val":"id","end":""},{"old":"/admin/files/:id/alts","type":0,"val":"alts","end":""}],
    types: placeholder as Registry['admin.files.delete_alt']['types'],
  },
  'admin.file_folders.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/files/folders',
    tokens: [{"old":"/admin/files/folders","type":0,"val":"admin","end":""},{"old":"/admin/files/folders","type":0,"val":"files","end":""},{"old":"/admin/files/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.file_folders.render']['types'],
  },
  'admin.file_folders.execute': {
    methods: ["POST"],
    pattern: '/admin/files/folders',
    tokens: [{"old":"/admin/files/folders","type":0,"val":"admin","end":""},{"old":"/admin/files/folders","type":0,"val":"files","end":""},{"old":"/admin/files/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.file_folders.execute']['types'],
  },
  'admin.file_folders.update': {
    methods: ["PUT"],
    pattern: '/admin/files/folders/:id',
    tokens: [{"old":"/admin/files/folders/:id","type":0,"val":"admin","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"files","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"folders","end":""},{"old":"/admin/files/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.file_folders.update']['types'],
  },
  'admin.file_folders.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/files/folders/:id',
    tokens: [{"old":"/admin/files/folders/:id","type":0,"val":"admin","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"files","end":""},{"old":"/admin/files/folders/:id","type":0,"val":"folders","end":""},{"old":"/admin/files/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.file_folders.destroy']['types'],
  },
  'admin.settings.maintenance.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/maintenance',
    tokens: [{"old":"/admin/settings/maintenance","type":0,"val":"admin","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"settings","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['admin.settings.maintenance.render']['types'],
  },
  'admin.settings.maintenance.update': {
    methods: ["POST"],
    pattern: '/admin/settings/maintenance',
    tokens: [{"old":"/admin/settings/maintenance","type":0,"val":"admin","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"settings","end":""},{"old":"/admin/settings/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['admin.settings.maintenance.update']['types'],
  },
  'admin.settings.maintenance.toggle': {
    methods: ["POST"],
    pattern: '/admin/settings/maintenance/toggle',
    tokens: [{"old":"/admin/settings/maintenance/toggle","type":0,"val":"admin","end":""},{"old":"/admin/settings/maintenance/toggle","type":0,"val":"settings","end":""},{"old":"/admin/settings/maintenance/toggle","type":0,"val":"maintenance","end":""},{"old":"/admin/settings/maintenance/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['admin.settings.maintenance.toggle']['types'],
  },
  'admin.logs.render': {
    methods: ["GET","HEAD"],
    pattern: '/admin/logs',
    tokens: [{"old":"/admin/logs","type":0,"val":"admin","end":""},{"old":"/admin/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['admin.logs.render']['types'],
  },
  'api.v1.admin.users_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['api.v1.admin.users_api.index']['types'],
  },
  'api.v1.admin.users_create_api.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['api.v1.admin.users_create_api.store']['types'],
  },
  'api.v1.admin.users_show_api.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.users_show_api.show']['types'],
  },
  'api.v1.admin.users_update_api.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.users_update_api.update']['types'],
  },
  'api.v1.admin.users_delete_api.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.users_delete_api.destroy']['types'],
  },
  'api.v1.admin.roles_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/roles',
    tokens: [{"old":"/api/v1/admin/roles","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['api.v1.admin.roles_api.index']['types'],
  },
  'api.v1.admin.roles_create_api.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/roles',
    tokens: [{"old":"/api/v1/admin/roles","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['api.v1.admin.roles_create_api.store']['types'],
  },
  'api.v1.admin.roles_show_api.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.roles_show_api.show']['types'],
  },
  'api.v1.admin.roles_update_api.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.roles_update_api.update']['types'],
  },
  'api.v1.admin.roles_delete_api.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/roles/:id',
    tokens: [{"old":"/api/v1/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.roles_delete_api.destroy']['types'],
  },
  'api.v1.admin.files_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/files',
    tokens: [{"old":"/api/v1/admin/files","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['api.v1.admin.files_api.index']['types'],
  },
  'api.v1.admin.files_upload_api.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/files',
    tokens: [{"old":"/api/v1/admin/files","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['api.v1.admin.files_upload_api.store']['types'],
  },
  'api.v1.admin.files_show_api.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/files/:id',
    tokens: [{"old":"/api/v1/admin/files/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.files_show_api.show']['types'],
  },
  'api.v1.admin.files_api.move': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/files/:id/move',
    tokens: [{"old":"/api/v1/admin/files/:id/move","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id/move","type":1,"val":"id","end":""},{"old":"/api/v1/admin/files/:id/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['api.v1.admin.files_api.move']['types'],
  },
  'api.v1.admin.files_delete_api.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/files/:id',
    tokens: [{"old":"/api/v1/admin/files/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.files_delete_api.destroy']['types'],
  },
  'api.v1.admin.files_alt_api.upsert_alt': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/files/:id/alt',
    tokens: [{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id/alt","type":1,"val":"id","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"alt","end":""}],
    types: placeholder as Registry['api.v1.admin.files_alt_api.upsert_alt']['types'],
  },
  'api.v1.admin.files_alt_api.delete_alt': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/files/:id/alt',
    tokens: [{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"api","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"files","end":""},{"old":"/api/v1/admin/files/:id/alt","type":1,"val":"id","end":""},{"old":"/api/v1/admin/files/:id/alt","type":0,"val":"alt","end":""}],
    types: placeholder as Registry['api.v1.admin.files_alt_api.delete_alt']['types'],
  },
  'api.v1.admin.folders_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/folders',
    tokens: [{"old":"/api/v1/admin/folders","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['api.v1.admin.folders_api.index']['types'],
  },
  'api.v1.admin.folders_api.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/folders',
    tokens: [{"old":"/api/v1/admin/folders","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['api.v1.admin.folders_api.store']['types'],
  },
  'api.v1.admin.folders_show_api.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/folders/:id',
    tokens: [{"old":"/api/v1/admin/folders/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.folders_show_api.show']['types'],
  },
  'api.v1.admin.folders_show_api.children': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/folders/:id/children',
    tokens: [{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id/children","type":1,"val":"id","end":""},{"old":"/api/v1/admin/folders/:id/children","type":0,"val":"children","end":""}],
    types: placeholder as Registry['api.v1.admin.folders_show_api.children']['types'],
  },
  'api.v1.admin.folders_update_api.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/folders/:id',
    tokens: [{"old":"/api/v1/admin/folders/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.folders_update_api.update']['types'],
  },
  'api.v1.admin.folders_delete_api.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/admin/folders/:id',
    tokens: [{"old":"/api/v1/admin/folders/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/folders/:id","type":0,"val":"folders","end":""},{"old":"/api/v1/admin/folders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.v1.admin.folders_delete_api.destroy']['types'],
  },
  'api.v1.admin.theme.execute': {
    methods: ["POST"],
    pattern: '/api/v1/admin/preferences/theme',
    tokens: [{"old":"/api/v1/admin/preferences/theme","type":0,"val":"api","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"preferences","end":""},{"old":"/api/v1/admin/preferences/theme","type":0,"val":"theme","end":""}],
    types: placeholder as Registry['api.v1.admin.theme.execute']['types'],
  },
  'api.v1.admin.dashboard_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/dashboard',
    tokens: [{"old":"/api/v1/admin/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/admin/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['api.v1.admin.dashboard_api.index']['types'],
  },
  'api.v1.admin.logs_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/logs',
    tokens: [{"old":"/api/v1/admin/logs","type":0,"val":"api","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['api.v1.admin.logs_api.index']['types'],
  },
  'api.v1.admin.maintenance_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/maintenance',
    tokens: [{"old":"/api/v1/admin/maintenance","type":0,"val":"api","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['api.v1.admin.maintenance_api.index']['types'],
  },
  'api.v1.admin.maintenance_api.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/maintenance',
    tokens: [{"old":"/api/v1/admin/maintenance","type":0,"val":"api","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['api.v1.admin.maintenance_api.update']['types'],
  },
  'api.v1.admin.maintenance_api.toggle': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/maintenance/toggle',
    tokens: [{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"api","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"maintenance","end":""},{"old":"/api/v1/admin/maintenance/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['api.v1.admin.maintenance_api.toggle']['types'],
  },
  'api.v1.admin.permissions_api.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/permissions',
    tokens: [{"old":"/api/v1/admin/permissions","type":0,"val":"api","end":""},{"old":"/api/v1/admin/permissions","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/permissions","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['api.v1.admin.permissions_api.index']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
