/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class AuthAccessTokenSchema extends BaseModel {
	static $columns = [
		'abilities',
		'createdAt',
		'expiresAt',
		'hash',
		'id',
		'lastUsedAt',
		'name',
		'tokenableId',
		'type',
		'updatedAt',
	] as const;
	$columns = AuthAccessTokenSchema.$columns;
	@column()
	declare abilities: string;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column.dateTime()
	declare expiresAt: DateTime | null;
	@column()
	declare hash: string;
	@column({ isPrimary: true })
	declare id: number;
	@column.dateTime()
	declare lastUsedAt: DateTime | null;
	@column()
	declare name: string | null;
	@column()
	declare tokenableId: number;
	@column()
	declare type: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime;
}

export class FileAltSchema extends BaseModel {
	static $columns = ['createdAt', 'fileId', 'id', 'key', 'locale', 'updatedAt', 'value'] as const;
	$columns = FileAltSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare fileId: number;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare key: string;
	@column()
	declare locale: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column()
	declare value: string;
}

export class FileFolderSchema extends BaseModel {
	static $columns = ['createdAt', 'id', 'name', 'parentId', 'updatedAt'] as const;
	$columns = FileFolderSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare name: string;
	@column()
	declare parentId: number | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class FileSchema extends BaseModel {
	static $columns = [
		'createdAt',
		'disk',
		'extension',
		'filename',
		'folderId',
		'id',
		'mimeType',
		'originalName',
		'path',
		'size',
		'updatedAt',
		'uploadedBy',
	] as const;
	$columns = FileSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare disk: string;
	@column()
	declare extension: string;
	@column()
	declare filename: string;
	@column()
	declare folderId: number | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare mimeType: string;
	@column()
	declare originalName: string;
	@column()
	declare path: string;
	@column()
	declare size: bigint | number;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column()
	declare uploadedBy: number | null;
}

export class LogEntrySchema extends BaseModel {
	static $columns = [
		'actorEmail',
		'actorId',
		'category',
		'context',
		'createdAt',
		'error',
		'id',
		'ip',
		'level',
		'message',
		'requestId',
		'userAgent',
	] as const;
	$columns = LogEntrySchema.$columns;
	@column()
	declare actorEmail: string | null;
	@column()
	declare actorId: number | null;
	@column()
	declare category: string;
	@column()
	declare context: any | null;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare error: any | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare ip: string | null;
	@column()
	declare level: string;
	@column()
	declare message: string;
	@column()
	declare requestId: string | null;
	@column()
	declare userAgent: string | null;
}

export class PageRevisionSchema extends BaseModel {
	static $columns = ['content', 'createdAt', 'createdBy', 'id', 'keep', 'pageTranslationId'] as const;
	$columns = PageRevisionSchema.$columns;
	@column()
	declare content: any;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare createdBy: number | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare keep: boolean;
	@column()
	declare pageTranslationId: number;
}

export class PageTranslationSchema extends BaseModel {
	static $columns = [
		'content',
		'createdAt',
		'id',
		'locale',
		'metaDescription',
		'metaTitle',
		'pageId',
		'publishedAt',
		'slug',
		'status',
		'title',
		'updatedAt',
	] as const;
	$columns = PageTranslationSchema.$columns;
	@column()
	declare content: any;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare locale: string;
	@column()
	declare metaDescription: string | null;
	@column()
	declare metaTitle: string | null;
	@column()
	declare pageId: number;
	@column.dateTime()
	declare publishedAt: DateTime | null;
	@column()
	declare slug: string;
	@column()
	declare status: string;
	@column()
	declare title: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class PageSchema extends BaseModel {
	static $columns = [
		'createdAt',
		'createdBy',
		'defaultLocale',
		'id',
		'isHomepage',
		'metaImageId',
		'updatedAt',
	] as const;
	$columns = PageSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare createdBy: number | null;
	@column()
	declare defaultLocale: string;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare isHomepage: boolean;
	@column()
	declare metaImageId: number | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class PermissionSchema extends BaseModel {
	static $columns = ['category', 'createdAt', 'description', 'id', 'isSystem', 'name', 'slug', 'updatedAt'] as const;
	$columns = PermissionSchema.$columns;
	@column()
	declare category: string;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column()
	declare description: string | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare isSystem: boolean;
	@column()
	declare name: string;
	@column()
	declare slug: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class RememberMeTokenSchema extends BaseModel {
	static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const;
	$columns = RememberMeTokenSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column.dateTime()
	declare expiresAt: DateTime;
	@column()
	declare hash: string;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare tokenableId: number;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime;
}

export class RolePermissionSchema extends BaseModel {
	static $columns = ['createdAt', 'id', 'permissionId', 'roleId'] as const;
	$columns = RolePermissionSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare permissionId: number;
	@column()
	declare roleId: number;
}

export class RoleSchema extends BaseModel {
	static $columns = ['createdAt', 'description', 'id', 'isSystem', 'name', 'slug', 'updatedAt'] as const;
	$columns = RoleSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column()
	declare description: string | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare isSystem: boolean;
	@column()
	declare name: string;
	@column()
	declare slug: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class TemplateSchema extends BaseModel {
	static $columns = [
		'blockType',
		'content',
		'createdAt',
		'createdBy',
		'description',
		'id',
		'name',
		'thumbnailId',
		'type',
		'updatedAt',
	] as const;
	$columns = TemplateSchema.$columns;
	@column()
	declare blockType: string | null;
	@column()
	declare content: any;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare createdBy: number | null;
	@column()
	declare description: string | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare name: string;
	@column()
	declare thumbnailId: number | null;
	@column()
	declare type: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class TokenSchema extends BaseModel {
	static $columns = [
		'attempts',
		'createdAt',
		'expiresAt',
		'id',
		'selector',
		'token',
		'type',
		'updatedAt',
		'userId',
	] as const;
	$columns = TokenSchema.$columns;
	@column()
	declare attempts: number;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column.dateTime()
	declare expiresAt: DateTime | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare selector: string | null;
	@column()
	declare token: string;
	@column()
	declare type: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column()
	declare userId: number | null;
}

export class UserPreferenceSchema extends BaseModel {
	static $columns = ['createdAt', 'id', 'locale', 'theme', 'updatedAt', 'userId'] as const;
	$columns = UserPreferenceSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare locale: string;
	@column()
	declare theme: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime;
	@column()
	declare userId: number;
}

export class UserSchema extends BaseModel {
	static $columns = [
		'apiRateLimit',
		'createdAt',
		'email',
		'emailVerifiedAt',
		'facebookId',
		'githubId',
		'googleId',
		'id',
		'password',
		'pendingEmail',
		'roleId',
		'twoFactorEnabled',
		'twoFactorRecoveryCodes',
		'twoFactorSecret',
		'updatedAt',
		'username',
	] as const;
	$columns = UserSchema.$columns;
	@column()
	declare apiRateLimit: number | null;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare email: string;
	@column.dateTime()
	declare emailVerifiedAt: DateTime | null;
	@column()
	declare facebookId: string | null;
	@column()
	declare githubId: string | null;
	@column()
	declare googleId: string | null;
	@column({ isPrimary: true })
	declare id: number;
	@column({ serializeAs: null })
	declare password: string | null;
	@column()
	declare pendingEmail: string | null;
	@column()
	declare roleId: number | null;
	@column()
	declare twoFactorEnabled: boolean;
	@column()
	declare twoFactorRecoveryCodes: string | null;
	@column()
	declare twoFactorSecret: string | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column()
	declare username: string;
}

export class WebhookDeliverySchema extends BaseModel {
	static $columns = [
		'contentType',
		'createdAt',
		'deliveryId',
		'error',
		'id',
		'ip',
		'payloadDigest',
		'processedAt',
		'receiver',
		'status',
		'userAgent',
	] as const;
	$columns = WebhookDeliverySchema.$columns;
	@column()
	declare contentType: string | null;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare deliveryId: string;
	@column()
	declare error: string | null;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare ip: string | null;
	@column()
	declare payloadDigest: string;
	@column.dateTime()
	declare processedAt: DateTime | null;
	@column()
	declare receiver: string;
	@column()
	declare status: string;
	@column()
	declare userAgent: string | null;
}
